version: "3.7"

services:
  nginx:
    image: nginx:alpine
    container_name: php_discord-nginx
    restart: unless-stopped
    ports:
      - 89:80
    volumes:
      - ./src:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - php_discord

  app:
    build:
      args:
        user: decole
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: php_discord
    container_name: php_discord-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
      - ./docker-compose/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - php_discord

  db:
    image: mysql:5.7.31
    container_name: php_discord-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: discord_bot
      MYSQL_ROOT_PASSWORD: homesteed
      MYSQL_PASSWORD: homesteed
      MYSQL_USER: laravel
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/.dev/mysql:/var/lib/mysql
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - php_discord

  phpmyadmin:
    image: phpmyadmin
    container_name: php_discord-phpmyadmin
    env_file:
      - ./src/.env
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      UPLOAD_LIMIT: 50M
      PMA_PMADB: discord_bot
    #    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions
    depends_on:
      - db
    networks:
      - php_discord

networks:
  php_discord:
    driver: bridge
