version: "3.7"

services:
  nginx:
    image: nginx:alpine
    container_name: php_discord-nginx
    restart: always
    ports:
      - 89:80
    volumes:
      - ./src:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - php_discord

  app:
    build:
      args:
        user: decole
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: php_discord
    container_name: php_discord-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
      - ./docker-compose/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - php_discord

networks:
  php_discord:
    driver: bridge
